# Generated by Django 5.1.2 on 2024-10-24 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0002_rename_price_component_repair_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='vehicleapp.component'),
        ),
    ]
